//Todo: Default post
export const CREATE_DEFAULT_POST_SUB = 'CREATE_DEFAULT_POST_SUB';
export const LIKE_DEFAULT_POST_SUB = 'LIKE_DEFAULT_POST_SUB';
export const COMMENT_DEFAULT_POST_SUB = 'COMMENT_DEFAULT_POST_SUB';
export const COMMENT_DEFAULT_POST_COUNT_SUB = 'COMMENT_DEFAULT_POST_COUNT_SUB';
//Todo: Recruiment post
export const CREATE_RECRUIMENT_POST_SUB = 'CREATE_RECRUIMENT_POST_SUB';
export const ATTEND_RECRUIMENT_POST_SUB = 'ATTEND_RECRUIMENT_POST_SUB';
export const COMMENT_RECRUIMENT_POST_SUB = 'COMMENT_RECRUIMENT_POST_SUB';
export const COMMENT_RECRUIMENT_POST_COUNT_SUB = 'COMMENT_RECRUIMENT_POST_COUNT_SUB';
//Todo: Message chat
export const CREATE_CHAT_MESSAGE_SUB = 'CREATE_CHAT_MESSAGE_SUB';
export const CREATE_CHAT_MESSAGE_NOTIFICATION_SUB = 'CREATE_CHAT_MESSAGE_NOTIFICATION_SUB';
